// colorburst update server: an Omaha v3 responder on Cloudflare Workers.
//
// update_engine POSTs Omaha XML to /update; we answer with either a
// noupdate or a manifest pointing at the payload on dl.colorburst.net
// (an R2 bucket with a custom domain). Release metadata lives in the
// same bucket as releases.json and is exactly the .json that
// cros_generate_update_payload emits, plus a "payload" file name and
// "channel" grouping -- see releases.example.json.
//
// Unlike nebraska (the reference implementation this follows), the
// client's version IS compared: a device already on target_version or
// newer gets noupdate, so identical-version reinstall loops can't happen.

const PAYLOAD_BASE = "https://dl.colorburst.net/payloads/";

function xmlEscape(s) {
  return String(s).replace(/[<>&"']/g,
    c => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" }[c]));
}

// ChromeOS platform versions compare component-wise: "16770.0.1" etc.
function versionLess(a, b) {
  const pa = String(a).split(".").map(Number);
  const pb = String(b).split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const x = pa[i] || 0, y = pb[i] || 0;
    if (x !== y) return x < y;
  }
  return false;
}

// Minimal XML attribute scraping -- the request is machine-generated by
// update_engine, so regex extraction against its fixed shape is fine.
function parseRequest(xml) {
  const app = xml.match(/<app\s[^>]*>/);
  if (!app) return null;
  const attr = (name) => {
    const m = app[0].match(new RegExp(`${name}="([^"]*)"`));
    return m ? m[1] : "";
  };
  // Omaha ping semantics: the CLIENT tracks when it last reported, so
  // each device sends at most one "active" ping per day. a/r are
  // days-since-last-report; -1 means first time ever (= new install).
  const ping = xml.match(/<ping\s[^>]*>|<ping\s*\/>/);
  const pattr = (name) => {
    if (!ping) return null;
    const m = ping[0].match(new RegExp(`${name}="(-?\\d+)"`));
    return m ? parseInt(m[1], 10) : null;
  };
  return {
    appid: attr("appid"),
    version: attr("version"),
    track: attr("track") || attr("channel") || "stable",
    board: attr("board"),
    // hardware_class = crossystem hwid: empty under crosvm/VMs, non-empty
    // on real hardware. Used to keep test traffic out of the fleet stats.
    // NOTE: on reven-based hardware this is the literal string "unknown" --
    // it identifies a firmware-declared model, and our boards declare none.
    hardwareClass: attr("hardware_class"),
    hasUpdateCheck: /<updatecheck[\s/>]/.test(xml),
    hasPing: !!ping,
    pingActive: pattr("active"),
    pingA: pattr("a"),
    pingR: pattr("r"),
  };
}

function noUpdateResponse(appid) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="colorburst">
 <daystart elapsed_seconds="0"/>
 <app appid="${xmlEscape(appid)}" status="ok">
  <ping status="ok"/>
  <updatecheck status="noupdate"/>
 </app>
</response>`;
}

// The package fp attribute is load-bearing: update_engine rejects a
// response whose package fp is missing or equal to the one it sent
// (kRepeatedFpFromOmahaError, omaha_request_action.cc:1360-1393; verified
// against a real client in OTA-CLIENT.md). Nebraska derives fp as
// "1." + hex sha256; same here, so it changes whenever the payload does.
function updateResponse(appid, rel) {
  const codebase = PAYLOAD_BASE + encodeURIComponent(rel.target_version) + "/";
  return `<?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="colorburst">
 <daystart elapsed_seconds="0"/>
 <app appid="${xmlEscape(appid)}" status="ok">
  <ping status="ok"/>
  <updatecheck status="ok">
   <urls><url codebase="${xmlEscape(codebase)}"/></urls>
   <manifest version="${xmlEscape(rel.target_version)}">
    <actions>
     <action event="update" run="${xmlEscape(rel.payload)}"/>
     <action event="postinstall" ChromeOSVersion="${xmlEscape(rel.target_version)}"
             ChromeVersion="1.0.0.0" IsDeltaPayload="${rel.is_delta ? "true" : "false"}"
             MetadataSize="${xmlEscape(rel.metadata_size)}"
             MetadataSignatureRsa="${xmlEscape(rel.metadata_signature)}"
             MaxDaysToScatter="14" DisablePayloadBackoff="false"/>
    </actions>
    <packages>
     <package name="${xmlEscape(rel.payload)}" size="${xmlEscape(rel.size)}"
              hash_sha256="${xmlEscape(rel.sha256_hex)}"
              fp="${xmlEscape("1." + rel.sha256_hex)}" required="true"/>
    </packages>
   </manifest>
  </updatecheck>
 </app>
</response>`;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/health") return new Response("ok\n");
    if (url.pathname !== "/update" || request.method !== "POST") {
      return new Response("colorburst update server\n", { status: 404 });
    }

    const body = await request.text();
    const req = parseRequest(body);
    if (!req || !req.appid) return new Response("bad request", { status: 400 });

    const relFile = await env.RELEASES.get("releases.json");
    const releases = relFile ? JSON.parse(await relFile.text()) : {};
    const rel = releases[req.track] || releases["stable"];

    // Telemetry tier 1: one row per update check -- version distribution
    // and active-device counts fall out of this. No identifiers stored.
    // Only real hardware carries a hardware_class; VMs (crosvm test boots)
    // send it empty. Gating telemetry on it keeps our own update-testing
    // out of the device counts -- otherwise every fresh-overlay VM boot
    // looks like a brand-new device sending its first-ever ping.
    if (env.PING && req.hardwareClass) {
      // One row per request. Fleet arithmetic (see README):
      //   daily actives  = rows/day with is_active_ping = 1
      //   new installs   = rows with is_first_ping = 1
      const isActivePing = req.pingA !== null && (req.pingA === -1 || req.pingA > 0);
      const isFirstPing = req.pingR === -1;
      env.PING.writeDataPoint({
        blobs: [req.version, req.track, req.board, rel ? rel.target_version : ""],
        doubles: [req.hasUpdateCheck ? 1 : 0, isActivePing ? 1 : 0, isFirstPing ? 1 : 0],
        indexes: [req.version],
      });
    }

    const wantsUpdate = rel && req.hasUpdateCheck &&
        rel.appid === req.appid &&
        versionLess(req.version, rel.target_version);

    const xml = wantsUpdate ? updateResponse(req.appid, rel)
                            : noUpdateResponse(req.appid);
    return new Response(xml, { headers: { "Content-Type": "text/xml" } });
  },
};
