// colorburst update server: an Omaha v3 responder on Cloudflare Workers.
//
// update_engine POSTs Omaha XML to /update; we answer with either a
// noupdate or a manifest pointing at the payload on dl.colorburst.net
// (an R2 bucket with a custom domain). Release metadata lives in the
// same bucket as releases.json and is exactly the .json that
// cros_generate_update_payload emits, plus a "payload" file name and
// "channel" grouping -- see releases.example.json.
//
// Unlike nebraska (the reference implementation this follows), the
// client's version IS compared: a device already on target_version or
// newer gets noupdate, so identical-version reinstall loops can't happen.

const OS_APPID = "{3EFFC3C6-5828-4F3A-967D-BAEA412E2DC8}";
const PAYLOAD_BASE = "https://dl.colorburst.net/payloads/";

// DLCs are NOT served from here. Crostini's DLCs (termina, termina-tools,
// edk2-ovmf) are force-ota: update_engine's InstallAction fetches the raw
// dlc.img straight from dl.colorburst.net/dlc/... and verifies it against the
// imageloader manifest hash baked into the rootfs -- Omaha is never consulted
// (see chromium-os release/DLC-RELEASE.md). A DLC-install request still
// reaches this server carrying one <app> per DLC (composite appid
// "{OS_APPID}_<dlc_id>"); each simply gets a well-formed noupdate below.

function xmlEscape(s) {
  return String(s).replace(/[<>&"']/g,
    c => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" }[c]));
}

// ChromeOS platform versions compare component-wise: "16770.0.1" etc.
function versionLess(a, b) {
  const pa = String(a).split(".").map(Number);
  const pb = String(b).split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const x = pa[i] || 0, y = pb[i] || 0;
    if (x !== y) return x < y;
  }
  return false;
}

// Minimal XML attribute scraping -- the request is machine-generated by
// update_engine, so regex extraction against its fixed shape is fine.
//
// An update check has one <app> (the platform app); a DLC install has the
// platform app (skip_update -> no <updatecheck>) followed by one <app> per DLC,
// each with its own <updatecheck> (omaha_request_builder_xml.cc:483-502, :488
// sets .skip_update = is_install()). So we parse EVERY app block and decide
// per-app, rather than only the first. hasUpdateCheck/ping are scoped to each
// app's own block so a skip_update platform app is correctly seen as no-check.
function parseAppBlock(block) {
  const attr = (name) => {
    const m = block.match(new RegExp(`${name}="([^"]*)"`));
    return m ? m[1] : "";
  };
  const ping = block.match(/<ping\s[^>]*>|<ping\s*\/>/);
  const pattr = (name) => {
    if (!ping) return null;
    const m = ping[0].match(new RegExp(`${name}="(-?\\d+)"`));
    return m ? parseInt(m[1], 10) : null;
  };
  return {
    appid: attr("appid"),
    version: attr("version"),
    track: attr("track") || attr("channel") || "stable",
    board: attr("board"),
    // hardware_class = crossystem hwid: empty under crosvm/VMs, non-empty
    // on real hardware. Used to keep test traffic out of the fleet stats.
    // NOTE: on reven-based hardware this is the literal string "unknown" --
    // it identifies a firmware-declared model, and our boards declare none.
    hardwareClass: attr("hardware_class"),
    // Opaque per-installation id minted by the colorburst-device-id upstart
    // job. Absent on USB/live and recovery boots, which are deliberately not
    // counted as devices; absent on VMs for the same reason. Never derived
    // from hardware, so it identifies an install, not a machine.
    deviceId: attr("colorburst_device_id"),
    hasUpdateCheck: /<updatecheck[\s/>]/.test(block),
    // Omaha ping semantics: the CLIENT tracks when it last reported, so
    // each device sends at most one "active" ping per day. a/r are
    // days-since-last-report; -1 means first time ever (= new install).
    hasPing: !!ping,
    pingActive: pattr("active"),
    pingA: pattr("a"),
    pingR: pattr("r"),
  };
}

// Return every <app> block, split on the app boundaries. update_engine always
// closes each app with </app>. If none match (malformed), returns [].
function parseRequest(xml) {
  const blocks = xml.match(/<app\b[\s\S]*?<\/app>/g);
  if (!blocks) return [];
  return blocks.map(parseAppBlock);
}

// One <response> wrapping one <app> per requested app. Splitting the document
// into per-app fragments is what lets a DLC-install request (platform app +
// several DLC apps) get an individually-correct answer for each app.
function wrapResponse(appFragments) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="colorburst">
 <daystart elapsed_seconds="0"/>
${appFragments.join("\n")}
</response>`;
}

function appNoUpdate(appid) {
  return ` <app appid="${xmlEscape(appid)}" status="ok">
  <ping status="ok"/>
  <updatecheck status="noupdate"/>
 </app>`;
}

// Kept for compatibility with any caller expecting a full document.
function noUpdateResponse(appid) {
  return wrapResponse([appNoUpdate(appid)]);
}

// The package fp attribute is load-bearing: update_engine rejects a
// response whose package fp is missing or equal to the one it sent
// (kRepeatedFpFromOmahaError, omaha_request_action.cc:1360-1393; verified
// against a real client in OTA-CLIENT.md). Nebraska derives fp as
// "1." + hex sha256; same here, so it changes whenever the payload does.
function appUpdate(appid, rel) {
  const codebase = PAYLOAD_BASE + encodeURIComponent(rel.target_version) + "/";
  return ` <app appid="${xmlEscape(appid)}" status="ok">
  <ping status="ok"/>
  <updatecheck status="ok">
   <urls><url codebase="${xmlEscape(codebase)}"/></urls>
   <manifest version="${xmlEscape(rel.target_version)}">
    <actions>
     <action event="update" run="${xmlEscape(rel.payload)}"/>
     <action event="postinstall" ChromeOSVersion="${xmlEscape(rel.target_version)}"
             ChromeVersion="1.0.0.0" IsDeltaPayload="${rel.is_delta ? "true" : "false"}"
             MetadataSize="${xmlEscape(rel.metadata_size)}"
             MetadataSignatureRsa="${xmlEscape(rel.metadata_signature)}"
             MaxDaysToScatter="14" DisablePayloadBackoff="false"/>
    </actions>
    <packages>
     <package name="${xmlEscape(rel.payload)}" size="${xmlEscape(rel.size)}"
              hash_sha256="${xmlEscape(rel.sha256_hex)}"
              fp="${xmlEscape("1." + rel.sha256_hex)}" required="true"/>
    </packages>
   </manifest>
  </updatecheck>
 </app>`;
}

// Kept for compatibility with any caller expecting a full document.
function updateResponse(appid, rel) {
  return wrapResponse([appUpdate(appid, rel)]);
}

// Stable 0-99 bucket for a device id: the same install always lands in the
// same bucket for a given release, so a percentage rollout is a growing set,
// never a per-request coin flip that would offer an update and then withdraw
// it. FNV-1a over id + target_version.
function rolloutBucket(deviceId, targetVersion) {
  let h = 0x811c9dc5;
  for (const ch of `${deviceId}@${targetVersion}`) {
    h ^= ch.charCodeAt(0);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h % 100;
}

// Decide whether this request's device may have `rel` yet. A release entry
// can carry either or both of:
//   "devices": ["<id>", ...]   only these installs (canary smoke test)
//   "rollout_percent": 0-100   this share of installs, stable per install
// Absent/invalid means "everyone", i.e. the previous behaviour.
//
// A device with no id (USB/live boot, VM, or an older build that predates the
// id) is treated as in-scope for an unrestricted release, but is never part
// of a targeted or partial one -- there is nothing stable to target it by.
function releaseAllowed(rel, deviceId) {
  const list = Array.isArray(rel.devices) ? rel.devices : null;
  const pct = Number.isFinite(rel.rollout_percent) ? rel.rollout_percent : null;
  if (!list && pct === null) return true;
  if (!deviceId) return false;
  if (list && !list.includes(deviceId)) return false;
  if (pct !== null && rolloutBucket(deviceId, rel.target_version) >= pct) {
    return false;
  }
  return true;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/health") return new Response("ok\n");
    if (url.pathname !== "/update" || request.method !== "POST") {
      return new Response("colorburst update server\n", { status: 404 });
    }

    const body = await request.text();
    const apps = parseRequest(body);
    if (!apps.length || !apps.some((a) => a.appid)) {
      return new Response("bad request", { status: 400 });
    }

    // The platform app carries the ping, device id, board and track; DLC apps
    // repeat board/track but never the ping/device id. Telemetry and OS-release
    // selection are driven by it, keeping single-app (pure update check)
    // behaviour byte-for-byte identical. Fall back to the first app if a
    // request somehow omits the platform app.
    const req = apps.find((a) => a.appid === OS_APPID) || apps[0];

    const relFile = await env.RELEASES.get("releases.json");
    const releases = relFile ? JSON.parse(await relFile.text()) : {};
    const rel = releases[req.track] || releases["stable"];

    // Telemetry tier 1: one row per update check -- version distribution
    // and active-device counts fall out of this. No identifiers stored.
    // Only real hardware carries a hardware_class; VMs (crosvm test boots)
    // send it empty. Gating telemetry on it keeps our own update-testing
    // out of the device counts -- otherwise every fresh-overlay VM boot
    // looks like a brand-new device sending its first-ever ping.
    // An install that carries a device id is by construction a real installed
    // device (the job that mints it skips USB/live and recovery boots), so
    // that is now the primary gate. hardware_class is kept as the fallback
    // for devices still on releases that predate the id -- but note it is
    // the literal "unknown" on reven hardware, which is why it could never
    // be more than a coarse VM filter.
    if (env.PING && (req.deviceId || req.hardwareClass)) {
      // One row per request. Fleet arithmetic (see README):
      //   daily actives  = rows/day with is_active_ping = 1
      //   new installs   = rows with is_first_ping = 1
      //   distinct fleet = COUNT(DISTINCT blob5) where blob5 <> ''
      const isActivePing = req.pingA !== null && (req.pingA === -1 || req.pingA > 0);
      const isFirstPing = req.pingR === -1;
      env.PING.writeDataPoint({
        blobs: [req.version, req.track, req.board, rel ? rel.target_version : "",
                req.deviceId || ""],
        doubles: [req.hasUpdateCheck ? 1 : 0, isActivePing ? 1 : 0, isFirstPing ? 1 : 0],
        indexes: [req.version],
      });
    }

    // Answer every requested app. Order preserved so the response mirrors the
    // request (update_engine matches by appid, not position, but this keeps it
    // readable and identical to the old single-app output).
    const fragments = apps.map((a) => {
      // Platform app: version-compared, track-selected, rollout-gated. Only
      // the app whose appid matches the release is offered an update. Every
      // other app -- a skip_update platform app, or the per-DLC apps of a DLC
      // install (served from the CDN, not from here; see the header) -- gets
      // a well-formed noupdate.
      const wantsUpdate = rel && a.hasUpdateCheck &&
          rel.appid === a.appid &&
          versionLess(a.version, rel.target_version) &&
          releaseAllowed(rel, a.deviceId);
      return wantsUpdate ? appUpdate(a.appid, rel) : appNoUpdate(a.appid);
    });

    return new Response(wrapResponse(fragments),
        { headers: { "Content-Type": "text/xml" } });
  },
};
